### PR TITLE
Extend nodebb-plugin-write-api to allow updates to the picture+uploadedpicture and settings

### PR DESCRIPTION
**Pull request by davidvuong**
Not sure if you guys want this exposed via the API but I needed this in an application I'm writing and thought this might be useful to the rest of the NodeBB community :smile: 

Feel free to close this PR if you think this isn't needed.

1. The `filter:user.updateProfile` hook was directly copied from (https://github.com/CoderDojo/nodebb-plugin-write-api/commit/55bcddf82ba12bb92a37a53065ed7613729f5627)
2. Sorry for the formatting changes in `plugin.json`. WebStorm decided it wanted json files to be consistent. I can revert those changes if you need me to.

What I've mostly done is just just added a new endpoint (`/api/v1/user/:id/settings`) and then updated the docs in the README.md file.

### CODE REVIEW

**Comment by davidvuong** [comment]
Doesn't seem like this will be merged in. I'm going to close this PR and continue to work off my fork.

**Comment by psychobunny** [comment]
5 days for a plugin usually isn't enough time. Because we manage so many plugins and of course core, its hard to keep track at times.

I suggest bothering @julianlam on our forums perhaps, he might want to merge this but just hadn't had the time to review and test yet.

**Comment by julianlam** [comment]
This is true, I'd recommend working off your fork and adding new features on separate branches for better organisation. You can always merge everything into your plugin's master branch for production use :smile:

**Comment by davidvuong** [comment]
@psychobunny Yep. No problem, I'll keep that in mind the next time I make a PR. :+1:

**Pull request closed without merging**
