### PR TITLE
Admin endpoint for adding a user to a group.

### PR DESCRIPTION
**Pull request by danieleisenhardt**
From the administration panel there is the option to add a user to a (private) group directly. This endpoint mirrors this functionality.

### CODE REVIEW

**Comment by julianlam** [comment]
Otherwise, LGTM when added 😄

**Comment by danieleisenhardt** [comment]
I've added the corresponding `DELETE` route.

**Comment by IvanMMM** [comment]
Woah! That's what I need 🍰 
Accept PR please :)

**Comment by julianlam** [comment]
v5.1.0

**Pull request merged**
